export type SectionNameTitulo1 = "blog" | "vblog";

export type SectionName =
  | "dedicatoria_y_agradecimiento"
  | "descripcion_del_problema"
  | "preguntas_objetivos_e_hipotesis"
  | "justificacion_de_la_investigacion"
  | "viabilidad"
  | "antecedentes"
  | "marco_teorico"
  | "unidades_de_analisis"
  | "diseno_general_de_la_investigacion"
  | "tecnicas_de_muestreo"
  | "tamano_de_muestra"
  | "conceptualizacion_de_variables"
  | "operacionalizacion_de_las_variables"
  | "fuente_de_recoleccion_de_datos"
  | "tecnica_de_recoleccion_de_datos"
  | "instrumentos_para_la_recoleccion_de_datos"
  | "escalas_de_medicion"
  | "confiabilidad_y_validez_de_las_escalas_de_medicion"
  | "metodos_para_el_analisis_de_datos"
  | "introduccion"
  | "parrafos_introductorios_del_capitulo_de_resultados"
  | "confiabilidad"
  | "normalidad_distribucion_de_la_muestra"
  | "resultados_demograficos"
  | "resultados_descriptivos"
  | "prueba_de_hipotesis"
  | "discusion"
  | "recomendaciones";
